export interface PresetSeed {
  id: string
  name: string
  category: string
  icon: string | null
  defaultPort: number
  upstreamProtocol: 'http' | 'https-trusted' | 'https-insecure'
  websocket: boolean
  suggestedSubdomain: string | null
  healthCheckPath: string | null
  healthCheckExpectStatus: number | null
  defaultHeaders: Record<string, string> | null
  notes: string | null
}

export const builtInPresets: PresetSeed[] = [
  // Virtualization
  {
    id: 'proxmox-ve',
    name: 'Proxmox VE',
    category: 'virtualization',
    icon: 'server',
    defaultPort: 8006,
    upstreamProtocol: 'https-insecure',
    websocket: true,
    suggestedSubdomain: 'pve',
    healthCheckPath: '/api2/json/version',
    healthCheckExpectStatus: 200,
    defaultHeaders: null,
    notes: 'Proxmox uses a self-signed cert on 8006 and WebSockets for the console.',
  },
  {
    id: 'proxmox-backup-server',
    name: 'Proxmox Backup Server',
    category: 'virtualization',
    icon: 'database-backup',
    defaultPort: 8007,
    upstreamProtocol: 'https-insecure',
    websocket: true,
    suggestedSubdomain: 'pbs',
    healthCheckPath: '/api2/json/version',
    healthCheckExpectStatus: 200,
    defaultHeaders: null,
    notes: 'PBS uses a self-signed cert on 8007 and WebSockets for task views.',
  },

  // Auth
  {
    id: 'authentik',
    name: 'Authentik',
    category: 'auth',
    icon: 'shield-check',
    defaultPort: 9000,
    upstreamProtocol: 'http',
    websocket: true,
    suggestedSubdomain: 'auth',
    healthCheckPath: '/-/health/live/',
    healthCheckExpectStatus: 204,
    defaultHeaders: null,
    notes: 'Authentik. Use port 9443 instead if you want TLS to the upstream.',
  },
  {
    id: 'authelia',
    name: 'Authelia',
    category: 'auth',
    icon: 'shield-check',
    defaultPort: 9091,
    upstreamProtocol: 'http',
    websocket: false,
    suggestedSubdomain: 'auth',
    healthCheckPath: '/api/health',
    healthCheckExpectStatus: 200,
    defaultHeaders: null,
    notes: null,
  },

  // Container management
  {
    id: 'portainer',
    name: 'Portainer',
    category: 'virtualization',
    icon: 'box',
    defaultPort: 9000,
    upstreamProtocol: 'http',
    websocket: true,
    suggestedSubdomain: 'portainer',
    healthCheckPath: '/api/system/status',
    healthCheckExpectStatus: 200,
    defaultHeaders: null,
    notes: 'Portainer uses WebSockets for container console attach.',
  },
  {
    id: 'dockge',
    name: 'Dockge',
    category: 'virtualization',
    icon: 'container',
    defaultPort: 5001,
    upstreamProtocol: 'http',
    websocket: true,
    suggestedSubdomain: 'dockge',
    healthCheckPath: null,
    healthCheckExpectStatus: null,
    defaultHeaders: null,
    notes: null,
  },

  // Monitoring
  {
    id: 'uptime-kuma',
    name: 'Uptime Kuma',
    category: 'monitoring',
    icon: 'activity',
    defaultPort: 3001,
    upstreamProtocol: 'http',
    websocket: true,
    suggestedSubdomain: 'status',
    healthCheckPath: '/',
    healthCheckExpectStatus: 200,
    defaultHeaders: null,
    notes: 'Uptime Kuma uses WebSockets for live dashboard updates.',
  },
  {
    id: 'grafana',
    name: 'Grafana',
    category: 'monitoring',
    icon: 'line-chart',
    defaultPort: 3000,
    upstreamProtocol: 'http',
    websocket: true,
    suggestedSubdomain: 'grafana',
    healthCheckPath: '/api/health',
    healthCheckExpectStatus: 200,
    defaultHeaders: null,
    notes: null,
  },
  {
    id: 'prometheus',
    name: 'Prometheus',
    category: 'monitoring',
    icon: 'flame',
    defaultPort: 9090,
    upstreamProtocol: 'http',
    websocket: false,
    suggestedSubdomain: 'prometheus',
    healthCheckPath: '/-/healthy',
    healthCheckExpectStatus: 200,
    defaultHeaders: null,
    notes: null,
  },

  // Storage / files
  {
    id: 'nextcloud',
    name: 'Nextcloud',
    category: 'storage',
    icon: 'cloud',
    defaultPort: 80,
    upstreamProtocol: 'http',
    websocket: true,
    suggestedSubdomain: 'cloud',
    healthCheckPath: '/status.php',
    healthCheckExpectStatus: 200,
    defaultHeaders: { 'X-Forwarded-Proto': 'https' },
    notes: 'Nextcloud requires X-Forwarded-Proto for proper trusted-domain handling.',
  },
  {
    id: 'minio-console',
    name: 'MinIO Console',
    category: 'storage',
    icon: 'hard-drive',
    defaultPort: 9001,
    upstreamProtocol: 'http',
    websocket: true,
    suggestedSubdomain: 'minio',
    healthCheckPath: '/minio/health/live',
    healthCheckExpectStatus: 200,
    defaultHeaders: null,
    notes: null,
  },

  // Media
  {
    id: 'plex',
    name: 'Plex Media Server',
    category: 'media',
    icon: 'film',
    defaultPort: 32400,
    upstreamProtocol: 'http',
    websocket: true,
    suggestedSubdomain: 'plex',
    healthCheckPath: '/identity',
    healthCheckExpectStatus: 200,
    defaultHeaders: null,
    notes: null,
  },
  {
    id: 'jellyfin',
    name: 'Jellyfin',
    category: 'media',
    icon: 'film',
    defaultPort: 8096,
    upstreamProtocol: 'http',
    websocket: true,
    suggestedSubdomain: 'jellyfin',
    healthCheckPath: '/health',
    healthCheckExpectStatus: 200,
    defaultHeaders: null,
    notes: null,
  },
  {
    id: 'sonarr',
    name: 'Sonarr',
    category: 'media',
    icon: 'tv',
    defaultPort: 8989,
    upstreamProtocol: 'http',
    websocket: true,
    suggestedSubdomain: 'sonarr',
    healthCheckPath: '/ping',
    healthCheckExpectStatus: 200,
    defaultHeaders: null,
    notes: null,
  },
  {
    id: 'radarr',
    name: 'Radarr',
    category: 'media',
    icon: 'film',
    defaultPort: 7878,
    upstreamProtocol: 'http',
    websocket: true,
    suggestedSubdomain: 'radarr',
    healthCheckPath: '/ping',
    healthCheckExpectStatus: 200,
    defaultHeaders: null,
    notes: null,
  },

  // Other common services
  {
    id: 'gitea',
    name: 'Gitea',
    category: 'other',
    icon: 'git-branch',
    defaultPort: 3000,
    upstreamProtocol: 'http',
    websocket: true,
    suggestedSubdomain: 'git',
    healthCheckPath: '/api/healthz',
    healthCheckExpectStatus: 200,
    defaultHeaders: null,
    notes: null,
  },
  {
    id: 'home-assistant',
    name: 'Home Assistant',
    category: 'other',
    icon: 'home',
    defaultPort: 8123,
    upstreamProtocol: 'http',
    websocket: true,
    suggestedSubdomain: 'ha',
    healthCheckPath: '/manifest.json',
    healthCheckExpectStatus: 200,
    defaultHeaders: null,
    notes: 'Home Assistant requires WebSockets and trusted-proxy config in configuration.yaml.',
  },
  {
    id: 'vaultwarden',
    name: 'Vaultwarden',
    category: 'auth',
    icon: 'key',
    defaultPort: 80,
    upstreamProtocol: 'http',
    websocket: true,
    suggestedSubdomain: 'vault',
    healthCheckPath: '/alive',
    healthCheckExpectStatus: 200,
    defaultHeaders: null,
    notes: null,
  },
]
